"""'Init'
Revision ID: cd39e09ba3da
Revises: ebc3716ded8c
Create Date: 2025-02-20 14:41:25.580024
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd39e09ba3da'
down_revision: Union[str, None] = 'ebc3716ded8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('test', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'test')
    # ### end Alembic commands ###
